---

- name: Create database `keystone`
  mysql_db:
    name: keystone
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: create user `keystone`
  mysql_user:
    name: keystone
    password: "{{ mysql_root_password }}"
    priv: 'keystone.*:ALL'
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    host: "{{ item }}"
  with_items:
    - localhost
    - "%"

- name: Don't start keystone service after installation. Will be started through apache instead
  shell: echo "manual" > /etc/init/keystone.override

- name: Install keystone and apache
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - keystone
    - apache2
    - libapache2-mod-wsgi

- name: Use this keystone config
  template:
    src: keystone/keystone.conf.j2
    dest: /etc/keystone/keystone.conf

- name: syncdb
  command: su -s /bin/sh -c "keystone-manage db_sync" keystone
  changed_when: false

- name: keystone fernet setup
  command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
  changed_when: false

- name: use this wsgi configuration
  template:
    src: keystone/wsgi-keystone.conf
    dest: /etc/apache2/sites-available/wsgi-keystone.conf

- name: link to sites-enabled
  file:
    src: /etc/apache2/sites-available/wsgi-keystone.conf
    dest: /etc/apache2/sites-enabled/wsgi-keystone.conf
    state: link
  notify:
    restart apache

- name: Bootstrap `keystone` admin & endpoint
  command: |
    su -s /bin/sh -c "/usr/bin/keystone-manage bootstrap \
    --bootstrap-username admin \
    --bootstrap-password rajalokan \
    --bootstrap-service-name keystone \
    --bootstrap-region-id RegionOne \
    --bootstrap-admin-url http://{{IP_ADDR}}:35357/v3/ \
    --bootstrap-internal-url http://{{IP_ADDR}}:5000/v3 \
    --bootstrap-public-url http://{{IP_ADDR}}:5000/v3" keystone
  changed_when: false

- name: Generate admin_openrc
  template:
    src: admin_openrc.j2
    dest: /opt/.admin_openrc

- name: Generate demo openrc
  template:
    src: demo_openrc.j2
    dest: /opt/.demo_openrc
