---
# - name: Setup database for keystone
#   mysql_db:
#     name: keystone
#     state: present
#     login_user: root
#     login_password: rajalokan
#
# - name: create user `keystone`
#   mysql_user:
#     name: keystone
#     password: rajalokan
#     priv: 'keystone.*:ALL'
#     state: present
#     login_user: root
#     login_password: rajalokan
#     host: "{{ item }}"
#   with_items:
#     - localhost
#     - "%"
#
# - name: Install keystone and apache
#   apt:
#     name: "{{ item }}"
#     state: installed
#   with_items:
#     - keystone
#     - apache2
#     - libapache2-mod-wsgi
#
# - name: Use this keystone config
#   template:
#     src: keystone/keystone.conf
#     dest: /etc/keystone/keystone.conf
#
# - name: syncdb
#   command: su -s /bin/sh -c "keystone-manage db_sync" keystone
#   become: true
#
# - name: keystone fernet setup
#   command: sudo keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
#   become: true
#
# - name: use this wsgi configuration
#   template:
#     src: keystone/wsgi-keystone.conf
#     dest: /etc/apache2/sites-available/wsgi-keystone.conf
#
# - name: link to sites-enabled
#   file:
#     src: /etc/apache2/sites-available/wsgi-keystone.conf
#     dest: /etc/apache2/sites-enabled/wsgi-keystone.conf
#     state: link
#

- debug: msg="http://{{ IP_ADDR }}:35357/v3"

- name: Get token
  os_auth:
    auth_type: token
    auth:
      token: 1234567890
      url: http://192.168.95.8:35357/v3
      identity_api_version: 3

- name: Create service keystone
  os_keystone_service:
    state: present
    name: keystone
    service_type: identity
    description: OpenStack Indentity
    auth_type: token
    auth:
      token: 1234567890
      url: "http://{{ IP_ADDR }}:35357/v3"
      identity_api_version: 3
