---

- name: Install rabbitmq-server
  apt:
    name: "{{ item }}"
    state: installed
  with_items: "{{ rabbitmq_apt_packages }}"

- name: Add user for rabbitmq-server
  rabbitmq_user:
    user: "{{ openstack_rabbitmq_username }}"
    password: "{{ openstack_rabbitmq_password }}"
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
