---

- name: Install rabbitmq-server
  apt:
    name: rabbitmq-server
    state: installed

- name: Add user for rabbitmq-server
  rabbitmq_user:
    user: openstack
    password: rajalokan
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present
